### ISSUE TITLE
kw接口搜索结果都是无音质。新歌无法下载

### ISSUE THREAD

**Issue by ClareDuan** [QiuChenlyOpenSource/QQFlacMusicDownloader#100]
kw接口搜索结果都是无音质。
最近的新歌都无法下载，下载到的都是拓展名是flac，实际是2秒的mp3文件
出问题的歌是7月29日发布的

准备开始下载任务
127.0.0.1 - - [30/Jul/2023 13:09:25] "POST /download HTTP/1.1" 200 -
正在下载 | ? / 希林娜依高 - 倒霉遇上你 [无音质]
不是无损文件，跳过元数据写入。
下载成功。

出问题的这首歌肯定不是付费歌曲，因为下面这首歌是这位歌手这张专辑中发布最早的歌，3月份发布的，是可以正常下载的。

准备开始下载任务
127.0.0.1 - - [30/Jul/2023 13:09:53] "POST /download HTTP/1.1" 200 -
正在下载 | ? / 希林娜依高 - 师傅，什么是爱情 [无音质]
正在查询... ? 希林娜依高 师傅，什么是爱情
? 希林娜依高 师傅，什么是爱情 没有匹配到iTunes曲库中的信息。
? 希林娜依高 师傅，什么是爱情 成功精确匹配到了QQ曲库信息。
下载成功。

**Comment by QiuChenly** [comment]
<img width="1292" alt="image" src="https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/24793281/2e233b18-5d07-427c-8dc0-f9b80672002b">

已在最新代码中FIX此问题。
