### ISSUE TITLE
元数据写入的一些建议

### ISSUE THREAD

**Issue by ClareDuan** [QiuChenlyOpenSource/QQFlacMusicDownloader#105]
由于不同的机型的播放器存在不同的差异，可能不支持艺术家分隔符为默认写入的";"导致歌曲信息变成乱码，以及无法读取内嵌歌词的问题，建议艺术家分隔符可在";" "/" "&" "、"中选择，并且让用户选择是否内嵌歌词还是下载lrc歌词文件。

**Comment by QiuChenly** [comment]
1. 这些工作虽然不是很麻烦但是比较费时。
2. 艺术家分割符乱码是因为FLAC文件TAG根据元数据标准数据类型读取出来是一个Array，我也只能存进去一个Array，读出来";"分割是程序的问题，他读出来array之后每个程序显示的方式不一样会用各种各样的符号做分割，这跟我的程序无关，你也控制不了。至于内嵌歌词，不支持显示内嵌歌词的播放器我觉得没有存在的必要。你也说了“根据不同的机型的播放器”，这是播放器的行为，跟我无关，我也控制不了这些播放器的行为。我建议你百度查一下音频文件元数据相关协议的文档再提这种问题。
4. 写入的数据歌曲信息变成乱码是因为你用的是windows，默认GBK编码，linux是UTF8。

总的来说，你提出的问题基本上都很有意思，但是基本都不是项目能解决的问题（除了歌词可以内置外置）。
如果需要单独lrc文件，可以单独使用一些Tag修改程序批量从音乐文件中导出。

**Comment by ClareDuan** [comment]
感谢解答。
单独lrc文件我当然知道可以用Tag修改程序批量从音乐文件中导出，不过如果一开始下载歌曲时就下载外置歌词岂不是更省时省力。
