### ISSUE TITLE
Dockerfile文件需要更新

### ISSUE THREAD

**Issue by Carlos920** [QiuChenlyOpenSource/QQFlacMusicDownloader#109]
由于添加了Pillow依赖，导致python-slim和python-aphine镜像无法愉快的打包了（缺少zlib和jpeg导致build Pillow失败）

需要在 `RUN pip3 install` 前添加以下步骤（会导致最终打包体积增大3倍）
```dockerfile
RUN apt-get update && apt-get install -y \
        gcc g++ libjpeg-dev zlib1g-dev \
        && rm -rf /var/lib/apt/lists/*
```

**Comment by QiuChenly** [comment]
增加这个库的原因是我无法找到一个合适的轻量级的Python处理Webp转jpeg并嵌入到音乐文件中😅
我迫切希望找到一个通用的轻量化解决方案解决此问题

**Comment by QiuChenly** [comment]
可以提一个pr。
