### ISSUE TITLE
请问大佬问题出在哪里 已经定位到出错的行数了

### ISSUE THREAD

**Issue by RenXuanJin** [QiuChenlyOpenSource/QQFlacMusicDownloader#121]
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/34950353/0f17c518-8bfa-48d3-914e-a148c89c3c35)
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/34950353/1e4faced-3521-42a2-8506-f9d05767e324)
请问是什么问题

**Comment by RenXuanJin** [comment]
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/34950353/d919a6f5-09da-4af1-b2ba-56979b728826)
是我的编码问题 还是url里面出错了？

**Comment by RenXuanJin** [comment]
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/34950353/4ec26cba-3e7e-40b0-b30e-b2b17e64f741)

**Comment by RenXuanJin** [comment]
这是python版本
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/34950353/42630da9-6c22-43fe-a77d-b2703890e70a)

**Comment by QiuChenly** [comment]
很佩服你的研究精神 我相信一个不懂技术的人能定位到报错位置已经很不容易了。
但是我想请你看看readme，已经说了网易云音乐接口已经挂了。
