### ISSUE TITLE
windwos 因为js被加载成text打不开的问题

### ISSUE THREAD

**Issue by zhovy** [QiuChenlyOpenSource/QQFlacMusicDownloader#124]
尝试按照猪猪的办法 在注册表找到 .js 
我本地的注册表没有这个值 我直接加上了重启项目和重启浏览器都没用,浏览器缓存也请了
还有其他办法吗 ？换mac🤣

发现源码里面的<script>标签里面的type='module'不知道有什么关系有没有
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/38269651/603245e2-9b2f-4433-8f1a-54777c2d1387)

![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/38269651/711f0ab7-c34a-48bd-8016-0c5fbfefdc31)
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/38269651/47b4db07-60f9-4f26-a28a-634891a5384a)

![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/38269651/eca62705-4a63-400a-bfbc-a23540aa1223)

**Comment by QiuChenly** [comment]
你这个问题应该不是改js解决  好像不是这个问题

**Comment by zhovy** [comment]
> 你这个问题应该不是改js解决 好像不是这个问题

不管了 一通瞎捣鼓 不如直接运行源码简单呢 跑源码可以打开 不知道是不是打包的问题
![Uploading image.png…]()
