### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by yuanyiming** [QiuChenlyOpenSource/QQFlacMusicDownloader#128]
Mac Studio macOS 14.0 beta通过git clone克隆尝试安装，安装依赖包完成，运行python3 MainServer.py提示先允许app.py，运行app.py出现报错，终端卡死

**Comment by QiuChenly** [comment]
你的操作有问题 只能运行python3 MainServer.py

**Comment by QiuChenly** [comment]
图呢哥们 你没图说个几8啊

**Comment by yuanyiming** [comment]
> 图呢哥们 你没图说个几8啊

不是哥们啊，这么大一晚上，我正准备下床开电脑给你拍照呢

**Comment by QiuChenly** [comment]
别急 看看你的

**Comment by yuanyiming** [comment]
> 别急 看看你的

![Uploading 截屏2023-08-30 下午11.08.36.png…]()

**Comment by QiuChenly** [comment]
![Uploading 截屏2023-08-30 下午11.08.36.png…]() 你发了个这个东西上来

**Comment by yuanyiming** [comment]
> 这样吧 我邮箱[qiuchenly@outlook.com](mailto:qiuchenly@outlook.com) 你可以直接发我邮箱

大佬看这里，我发送了，高清点

**Comment by QiuChenly** [comment]
你好像不是程序员。

我指出三个问题:
1. #号根本不能执行 你到底在执行什么我不懂
2. 
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/24793281/522bf689-1758-41ea-8250-182c506fe201)
已经提示你了python版本要大于3.7
3. 
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/24793281/9ccad471-6db9-4f4c-aea2-b5ce5ff85b53)
显然第一步没有成功一路失败到底。

**Comment by yuanyiming** [comment]
> 你好像不是程序员。
> 
> 我指出三个问题:
> 
> 1. #号根本不能执行 你到底在执行什么我不懂
> 
> ![image](https://user-images.githubusercontent.com/24793281/264390470-522bf689-1758-41ea-8250-182c506fe201.png) 已经提示你了python版本要大于3.7 3. ![image](https://user-images.githubusercontent.com/24793281/264390600-9ccad471-6db9-4f4c-aea2-b5ce5ff85b53.png) 显然第一步没有成功一路失败到底。

是的，我只是爱好，可是我装的python3.10，终端输入python3 -v显示也是3.10

**Comment by yuanyiming** [comment]
> 你好像不是程序员。
> 
> 我指出三个问题:
> 
> 1. #号根本不能执行 你到底在执行什么我不懂
> 
> ![image](https://user-images.githubusercontent.com/24793281/264390470-522bf689-1758-41ea-8250-182c506fe201.png) 已经提示你了python版本要大于3.7 3. ![image](https://user-images.githubusercontent.com/24793281/264390600-9ccad471-6db9-4f4c-aea2-b5ce5ff85b53.png) 显然第一步没有成功一路失败到底。

我前几天还是好的能运行，但是下载不了歌了我就重装，现在用的docker版本能运行，可是QQ音乐下载403，网易云下载没反应

**Comment by QiuChenly** [comment]
Docker版本很低哥们。。。

**Comment by yuanyiming** [comment]
> Docker版本很低哥们。。。而且docker镜像不是我维护的

不好意思啊哥，您说我运行的#号其实是我复制的这个
![IMG_4283](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/109521734/d2290016-e0ee-4b98-9d0a-49b6299f11bf)

**Comment by yuanyiming** [comment]
> 你运行“ # 安装依赖 ” 这干啥我没懂

我点边上的复制就这样了...

**Comment by QiuChenly** [comment]
下次记得不要带上#后面的内容

**Comment by yuanyiming** [comment]
> 下次记得不要带上#后面的内容

记住了，谢谢哥

**Comment by QiuChenly** [comment]
这是注释让人看的不是让电脑运行的
