### ISSUE TITLE
可以考虑----增加网页图标Favicon

### ISSUE THREAD

**Issue by VectorZhao** [QiuChenlyOpenSource/QQFlacMusicDownloader#139]
# 放在这个位置
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/16644993/42ec27d0-a527-4d4f-8617-a2f809772935)

# 我利用素材堆叠了一个
## 设计理念：漂流，音乐，下载到文件夹
![music-library](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/16644993/05b0ab9b-2b89-4154-813e-5d7b8b538de1)

**Comment by QiuChenly** [comment]
哦草 还有UI大佬啊！mark了

**Comment by VectorZhao** [comment]
我可真就能搞个图标。项目的主页UI确实需要优化一下，看看其他人有没有PR的吧。

**Comment by QiuChenly** [comment]
已增加。
