### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by lsdlh** [QiuChenlyOpenSource/QQFlacMusicDownloader#149]
qq歌单音乐下载失败，
歌词适配里面可以正常下载，这里却下载失败，是同一个接口吗？
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/45959509/05b694ec-2562-48fe-9854-ed8061637f4b)

**Comment by itscolor** [comment]
我QQ音乐也是无法下载了，请问如何解决呢？

**Comment by QiuChenly** [comment]
https://t.me/+u50LkfLuK8I1OGY1
交流群

**Comment by xzw2935** [comment]
我是qq能下网易不行

**Comment by QiuChenly** [comment]
妈的网易接口早挂了 不看readme是吧？

**Comment by xzw2935** [comment]
> 妈的网易接口早挂了 不看readme是吧？

忘了（）但是除了qq都用不了了我截图发tg了

**Comment by itscolor** [comment]
> 妈的网易接口早挂了 不看readme是吧？

请问开发者，那我QQ音乐显示已提交下载，实际却没有下载，是什么情况呢？docker-compose部署的.

**Comment by QiuChenly** [comment]
可能是docker有问题 你发邮件给docker维护者

**Comment by lsdlh** [comment]
> https://t.me/+u50LkfLuK8I1OGY1 交流群

已加，今天试了下qq下载又恢复了，程序都没有重启，docker部署的

**Comment by lsdlh** [comment]
已解决
