### ISSUE TITLE
可用的QQ音乐源

### ISSUE THREAD

**Issue by TwilightLemon** [QiuChenlyOpenSource/QQFlacMusicDownloader#171]
这个是项目中gcsp.kzti.top的官方App：
https://docs.qq.com/doc/DYW5yT0puVHdVeGh2

我发现有强制版本更新(App端和服务器api双验证)
目前版本4.1.4中  你的项目中的方法可行(EncryptTools.testGetLink)
需要修改json中的text_2,以及时间戳签名中MD5加密的盐
正如 https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/commit/ac81ca52293815ffe4b7ff8621ee96d75d5e9d27 中更新的那样，其他的加密方法和参数和之前版本一致

问题就在这里，我反编译了apk但是找不到....
大佬有方法么?

**Comment by Huibq** [comment]
> 这个是项目中gcsp.kzti.top的官方App： https://docs.qq.com/doc/DYW5yT0puVHdVeGh2
> 
> 我发现有强制版本更新(App端和服务器api双验证) 目前版本4.1.4中 你的项目中的方法可行(EncryptTools.testGetLink) 需要修改json中的text_2,以及时间戳签名中MD5加密的盐 正如 [ac81ca5](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/commit/ac81ca52293815ffe4b7ff8621ee96d75d5e9d27) 中更新的那样，其他的加密方法和参数和之前版本一致
> 
> 问题就在这里，我反编译了apk但是找不到.... 大佬有方法么?

原因加密方式放到了so文件里，需要ida来反编译

**Comment by QiuChenly** [comment]
事实上他那个so根本不用看 因为只是加密过程隐藏了 最终还是会调用java层加密 你们可以看我的md文档笔记 好像有描述到这一段

**Comment by QiuChenly** [comment]
所以大家可以直接用frida hook掉加密函数入口 读一下加密前的各个参数 就能拿到正确的md5值和明文值
