### ISSUE TITLE
Flac files downloaded from QQ are corrupted

### ISSUE THREAD

**Issue by mokapod** [QiuChenlyOpenSource/QQFlacMusicDownloader#176]
Every single flac files downloaded from QQ音乐 are corrupted when verified with xACT.

Files downloaded from 网易云音乐 or 酷我音乐 are fine.

**Comment by QiuChenly** [comment]
no, that not corrupted, bcuz im add more about music meta message e.g. lyrics singer songer.... so that's not corrupted

**Comment by mokapod** [comment]
Is there anyway to download without the extra metadata? Thanks

**Comment by QiuChenly** [comment]
why u need it? if u download that music file without Music Meta Information, u just will got an no any information's music file and not have any Album image/SongerName / SIngerName/Lyrics... when u arrange the music file , u got feel " it's tooo  crazy & chaos"

**Comment by mokapod** [comment]
No, it is just for testing purpose to see if the downloaded file is actually not corrupted.

Even files downloaded from other sources like Deezer or Qobuz can occasionally be corrupted so a re-download is necessary.

This is an example of error message:

刘若英 - 为爱痴狂.flac: testing, 55.000000% complete
刘若英 - 为爱痴狂.flac: 
刘若英 - 为爱痴狂.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


刘若英 - 为爱痴狂.flac: ERROR during decoding
                               state = FLAC__STREAM_DECODER_END_OF_STREAM

I still got this error after removing all the metadata. I am using xACT.

**Comment by QiuChenly** [comment]
oh, it's happening an mistakes, but the file's size are fully downloaded？

**Comment by mokapod** [comment]
Files are fully downloaded. No problem playing too.
Every single files from QQ got error even after redownload, but those from 网易云音乐 passed the verification.

**Comment by QiuChenly** [comment]
seem's it is Tencent Server Response Music Stream have an error data fragment, i can't fix it.

**Comment by mokapod** [comment]
Ok, thanks. You have done a great job from your end. Thank you again
