### ISSUE TITLE
使用咪咕搜索出现状态码500错误

### ISSUE THREAD

**Issue by WoodsTide** [QiuChenlyOpenSource/QQFlacMusicDownloader#53]
代码为最新版本
依赖均为最新版本

日志：
[0502.txt](https://github.com/QiuChenly/QQFlacMusicDownloader/files/11370243/0502.txt)

**Comment by QiuChenly** [comment]
原因是api.dog886.com这个服务器已经挂掉 这是用于搜索解析歌曲的服务器 请切换其他接口吧

**Comment by WoodsTide** [comment]
> 

谢谢
