### ISSUE TITLE
web界面有问题

### ISSUE THREAD

**Issue by 2263075977** [QiuChenlyOpenSource/QQFlacMusicDownloader#67]
群晖 使用本项目打包好的容器进行部署
![1685919386467](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/60037803/0c916406-8dab-436e-bbed-bf756c544f3b)

相关日志如下
2023/06/05 06:51:29 | stdout | 192.168.123.164 - - [04/Jun/2023 22:51:29] "GET /getConfig HTTP/1.1" 200 -
2023/06/05 06:51:29 | stdout | 192.168.123.164 - - [04/Jun/2023 22:51:29] "[36mGET /assets/index-77d4dafe.css HTTP/1.1[0m" 304 -
2023/06/05 06:51:29 | stdout | 192.168.123.164 - - [04/Jun/2023 22:51:29] "[36mGET /assets/index-1d4497e6.js HTTP/1.1[0m" 304 -
2023/06/05 06:51:29 | stdout | 192.168.123.164 - - [04/Jun/2023 22:51:29] "[36mGET /index.html HTTP/1.1[0m" 304 -
2023/06/05 06:51:23 | stdout | [33mPress CTRL+C to quit[0m
2023/06/05 06:51:23 | stdout | * Running on http://192.168.123.80:8899
2023/06/05 06:51:23 | stdout | * Running on http://127.0.0.1:8899
2023/06/05 06:51:23 | stdout | * Running on all addresses (0.0.0.0)
2023/06/05 06:51:23 | stdout | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
2023/06/05 06:51:23 | stdout | * Debug mode: off
2023/06/05 06:51:23 | stdout | * Serving Flask app 'flaskSystem.App'
2023/06/05 06:51:23 | stdout | kw_token已生成 I35ZTSOYGK

**Comment by QiuChenly** [comment]
该问题是浏览器的兼容问题，由于有些css代码在部分Windows上展现出的效果出现了异常，导致侧边栏无法出现，请更换浏览器。

**Comment by 2263075977** [comment]
> 该问题是浏览器的兼容问题，由于有些css代码在部分Windows上展现出的效果出现了异常，导致侧边栏无法出现，请更换浏览器。

好的 感谢
