### ISSUE TITLE
ARM Debian,用 DOCKER COMPOSE部署报错 python3: exec format error

### ISSUE THREAD

**Issue by lsyyktv** [QiuChenlyOpenSource/QQFlacMusicDownloader#75]
ARM Debian,用 DOCKER COMPOSE部署报错 python3: exec format error
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/39065858/78fd3760-c95c-4403-a893-9fd1b435ac24)

**Comment by lsyyktv** [comment]
> 这是你安装的python版本有问题啊

![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/39065858/2b6e8f45-fdd3-4e9d-aeff-52418b7bf9d4)
好像是compose image不兼容arm

**Comment by QiuChenly** [comment]
这个Docker镜像由爱好者上传，显然并不支持ARM版本机器。如果你需要使用可以自己拉项目python代码重新部署。

**Comment by lsyyktv** [comment]
好的，我用python重新部署，谢谢大佬！
