### ISSUE TITLE
已经保存新的下载目录，但重启后会重置

### ISSUE THREAD

**Issue by lsyyktv** [QiuChenlyOpenSource/QQFlacMusicDownloader#76]
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/39065858/df413eba-ad0b-40f8-9097-3d2eb2c87ad3)
拉的源代码部署的，更改下载目录后会立即生效，但是重启后又会还原成默认路径。

**Comment by QiuChenly** [comment]
如果你用docker 请自定义映射路径到本地，启动docker的时候带上映射信息。
出现这个问题是因为docker上似乎不会保存前端的session导致每次启动docker都会清空session，倒霉的是这些配置信息我只存在了浏览器session会话中，所以会重置。
后期考虑保存到磁盘上。

**Comment by lsyyktv** [comment]
> 如果你用docker 请自定义映射路径到本地，启动docker的时候带上映射信息。 出现这个问题是因为docker上似乎不会保存前端的session导致每次启动docker都会清空session，倒霉的是这些配置信息我只存在了浏览器session会话中，所以会重置。 后期考虑保存到磁盘上。

不是docker，就是直接拉源码部署的，因为vps是arm的，这个docker镜像暂时没法支持arm

**Comment by QiuChenly** [comment]
问题已经在最新的推送中使用本地config文件解决。
