### ISSUE TITLE
关于下载文件重命名的建议

### ISSUE THREAD

**Issue by cow-your-sister** [QiuChenlyOpenSource/QQFlacMusicDownloader#78]
可以做的想电脑版网易云/QQ音乐一样
可以选择开关“按歌手名分文件夹”，还有选择按照“歌曲名-歌手”命名还是“歌手-歌曲名”命名。
可以写成正则或者占位符这类的方式，方便自定义

**Comment by QiuChenly** [comment]
以后会考虑但是并不一定会采纳。
目前在计划同时写入内嵌歌词和专辑信息方便emby之类的媒体服务正确识别资源，所以你这个问题基本上不需要解决，只要让播放软件能正确识别信息就不用管文件怎么分类了。
