### ISSUE TITLE
QQ 音乐可以下，其它都不可以

### ISSUE THREAD

**Issue by gtpeter** [QiuChenlyOpenSource/QQFlacMusicDownloader#79]
首先，非常感谢该软件开发者QiuChenly 及其合作人员的大力开发，虽然还有很多不尽人意之处，但总比没有强！

本人目前在海外，今天2023年6月21日，在Win10 笔记本上安装了这款软件，安装和运行都很顺利。以下是本人其它的体检：

1. QQ，网易 和 酷我音乐 都可以搜索，而且很快； 但只有QQ音乐可以下，其它2个都不可以
2. 咪咕 和 MyFreeMP3 搜索不到任何资源
3. 用网易云音乐App 无法扫描二维码。 后来仔细看到介绍页面上面说是来自第三方网易云API服务器。（网易也是，想更换密码，都没有直接的页面改，说什么修正账号，然后连接网易游戏服务，算了，希望我的账号无事）。 手机上没有其它网易App ，所以没有再去试。 
4. 最后，不知是否可以在以后版本的设置中选择 **不同的音乐品质**来下载。 由于本人对音乐品质要求不高，再加上下载后的音乐都会存放到手机或云盘中，空间十分有限。 希望给与考虑, 谢谢！

**Comment by QiuChenly** [comment]
1.不会提供低音质的下载接口，所有的后端函数全都是自动按照最高音质来获取资源。
2.网易云扫码登录这个功能确实有点问题，你扫码登录不了是因为第三方服务器抽风。事实上我自己用过几回发现串号经常会出现陌生人的账号数据的时候我就不用了，这个服务器提供者确实有问题，他的后端系统没有做session隔离是真的不能忍。
3.别的接口都挂了，qq接口都还没挂我确实没想到。

**Comment by olbb** [comment]
>  2.网易云扫码登录这个功能确实有点问题，你扫码登录不了是因为第三方服务器抽风。事实上我自己用过几回发现串号经常会出现陌生人的账号数据的时候我就不用了，这个服务器提供者确实有问题，他的后端系统没有做session隔离是真的不能忍。

这个是由于Binaryify/NeteaseCloudMusicApi 的接口会根据url地址做缓存， 如果使用了post请求调用扫码登录接口，可以考虑在url后增加随机数作为url参数，以免命中其他人的缓存。

**Comment by QiuChenly** [comment]
QQ/MyFreeMP3/酷我现在全部正常。
