### ISSUE TITLE
适配手机浏览

### ISSUE THREAD

**Issue by VectorZhao** [QiuChenlyOpenSource/QQFlacMusicDownloader#84]
![2023-07-09 21 26 03](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/16644993/b852dff3-272c-4fc3-bce3-134cde04a66f)
手机浏览网页目前基本处于无法使用状态。手机搜搜歌，下载一下还是很常用的。希望开发者适配一下。

**Comment by QiuChenly** [comment]
因为这个一开始就不是给手机用的，只是恰好使用的技术为前端技术栈+服务器后端系统构建让跨端成为可能。
后期会考虑。

**Comment by VectorZhao** [comment]
感谢开发者，期待早日适配手机端浏览。

**Comment by wangweitung** [comment]
是不是也没适配Firefox？第一次打开我以为部署出错了。

![图片](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/8080125/ef698f78-1ddb-4958-9e6a-883d2213097b)

**Comment by QiuChenly** [comment]
初步优化手机端响应式页面.
提交详情参阅: b1d5bfa8ec3285219b14b3fd5bd6163a77edaf8d

**Comment by VectorZhao** [comment]
新版本


 Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8899
 * Running on http://192.168.125.104:8899
Press CTRL+C to quit
172.17.0.9 - - [24/Jul/2023 00:59:55] "GET / HTTP/1.1" 302 -
172.17.0.9 - - [24/Jul/2023 00:59:56] "GET /index.html HTTP/1.1" 404 -
172.17.0.9 - - [24/Jul/2023 00:59:57] "GET /favicon.ico HTTP/1.1" 404 -
172.17.0.9 - - [24/Jul/2023 01:00:07] "GET / HTTP/1.1" 302 -
192.168.125.103 - - [24/Jul/2023 01:00:08] "GET /index.html HTTP/1.1" 404 -
192.168.125.100 - - [24/Jul/2023 01:01:41] "GET / HTTP/1.1" 302 -
192.168.125.100 - - [24/Jul/2023 01:01:42] "GET /index.html HTTP/1.1" 404 -
192.168.125.100 - - [24/Jul/2023 01:01:45] "GET /favicon.ico HTTP/1.1" 404 -

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.###

**Comment by QiuChenly** [comment]
已经重新推送。

**Comment by VectorZhao** [comment]
搜不出东西来。。。。。点搜索，什么结果都没有
```
172.17.0.9 - - [24/Jul/2023 14:35:20] "GET / HTTP/1.1" 302 -
172.17.0.9 - - [24/Jul/2023 14:35:21] "GET /index.html HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:35:22] "GET /assets/index-06082f79.js HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:35:22] "GET /assets/index-59482b40.css HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:35:47] "GET /index.html HTTP/1.1" 304 -
172.17.0.9 - - [24/Jul/2023 14:35:58] "GET /assets/index-06082f79.js HTTP/1.1" 304 -
172.17.0.9 - - [24/Jul/2023 14:35:58] "GET /assets/index-59482b40.css HTTP/1.1" 304 -
172.17.0.9 - - [24/Jul/2023 14:36:37] "GET /index.html HTTP/1.1" 304 -
172.17.0.9 - - [24/Jul/2023 14:38:25] "GET / HTTP/1.1" 302 -
172.17.0.9 - - [24/Jul/2023 14:38:26] "GET /index.html HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:38:28] "GET /assets/index-06082f79.js HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:38:28] "GET /assets/index-59482b40.css HTTP/1.1" 200 -
172.17.0.9 - - [24/Jul/2023 14:38:30] "GET /vite.svg HTTP/1.1" 404 -

```

**Comment by QiuChenly** [comment]
刚推送，忘了上传了。
