### ISSUE TITLE
部分专辑歌曲只能下载一小段音频

### ISSUE THREAD

**Issue by qppq54s** [QiuChenlyOpenSource/QQFlacMusicDownloader#86]
<img width="681" alt="屏幕快照 2023-07-14 的 10 33 44 上午" src="https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/12963415/6c24f0d3-7e2e-4170-9783-772b1ed15356">
例如这个专辑第一首歌，只有2.6M，只能听到前面一小段歌曲

**Comment by QiuChenly** [comment]
这个问题应该是qq音乐资源解析服务器的问题，可能解决不了
