### ISSUE TITLE
QQ音乐部分歌曲下载后无法打开

### ISSUE THREAD

**Issue by otomad** [QiuChenlyOpenSource/QQFlacMusicDownloader#89]
下载部分QQ音乐的歌曲，控制台显示成功下载，但是找到对应歌曲文件后发现这些歌曲为大小64字节的文件，无法正常播放。

使用记事本打开该“flac”文件，显示为JSON错误信息。
```json
{"errorcode":-46628,"errormsg":"file not exist, retcode:-46628"}
```

<details>
<summary>控制台截图</summary>

![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/56647156/f92b6f73-f7c9-4d86-86d1-f98068d3fca8)
</details>

**Comment by QiuChenly** [comment]
因为这遇到了一些问题，我正在尝试解决but seems can't resolved.

**Comment by QiuChenly** [comment]
目前QQ搜索接口已经寄了。
