### ISSUE TITLE
下载音乐时，能否同时下载缩略图？

### ISSUE THREAD

**Issue by wangweitung** [QiuChenlyOpenSource/QQFlacMusicDownloader#90]
下载音乐时，能否同时下载缩略图？

**Comment by QiuChenly** [comment]
专辑歌词封面嵌入已经在计划中但是最近不会开发

**Comment by StrollStars** [comment]
@QiuChenly 支持这个建议，不太理解嵌入是什么意思，就像歌词文件那样处理就好——单独一个文件和歌曲本身放在一起。

**Comment by QiuChenly** [comment]
已支持下载音乐后自动填充对应的专辑信息歌手详情和专辑封面，以及内嵌歌词文件，方便Emby等影音库扫描归类。

**Comment by wangweitung** [comment]
> 已支持下载音乐后自动填充对应的专辑信息歌手详情和专辑封面，以及内嵌歌词文件，方便Emby等影音库扫描归类。

感谢大佬们这么好的作品。

**Comment by wangweitung** [comment]
> 已支持下载音乐后自动填充对应的专辑信息歌手详情和专辑封面，以及内嵌歌词文件，方便Emby等影音库扫描归类。

docker版是不是还没更新。。。

**Comment by QiuChenly** [comment]
问题已经使用内嵌歌词数据和歌曲元数据解决。

**Comment by wangweitung** [comment]
> 已支持下载音乐后自动填充对应的专辑信息歌手详情和专辑封面，以及内嵌歌词文件，方便Emby等影音库扫描归类。

能否增加一个选项：选择lrc歌词内嵌，或者单独与音乐文件放一起。

原因：如果内嵌，emby无法显示歌词。
emby只能显示单独文件的lrc歌词。

**Comment by QiuChenly** [comment]
emby可以读取内嵌的歌词文件。因为我现在就是这么用的。

**Comment by QiuChenly** [comment]
emby读不出来歌词只能说你文件有问题，用新代码下载的歌曲都会自带这些信息

**Comment by wangweitung** [comment]
> emby读不出来歌词只能说你文件有问题，用新代码下载的歌曲都会自带这些信息

感谢大佬。
我确实用的新的代码下载的文件。
可能是我emby的问题，我自己排查下。

**Comment by wangweitung** [comment]
![图片](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/8080125/3ed1e523-65dc-42b8-9ec4-c9d3be06e678)

**Comment by wangweitung** [comment]
> > emby读不出来歌词只能说你文件有问题，用新代码下载的歌曲都会自带这些信息
> 
> 感谢大佬。 我确实用的新的代码下载的文件。 可能是我emby的问题，我自己排查下。

是我服务端的问题，关闭issue

**Comment by StrollStars** [comment]
@wangweitung 你下载的有专辑封面吗？我下载[寄明月](https://y.qq.com/n/ryqq/songDetail/002yP4Gd0Mjr30)怎么看起来没有？FB2K和Mp3tag都没看到有封面。

**Comment by QiuChenly** [comment]
> @wangweitung 你下载的有专辑封面吗？我下载[寄明月](https://y.qq.com/n/ryqq/songDetail/002yP4Gd0Mjr30)怎么看起来没有？FB2K和Mp3tag都没看到有封面。

看首页说明啊，2个小时前还没有支持QQ音乐下载歌曲元数据补全！

**Comment by StrollStars** [comment]
@QiuChenly 没有问题，非常感谢。
