### ISSUE TITLE
建议支持远程下载

### ISSUE THREAD

**Issue by StrollStars** [QiuChenlyOpenSource/QQFlacMusicDownloader#91]
服务开启后支持本地访问（默认127.0.0.1:8899）和远程访问，但是下载时却只能下载到本地，希望能够支持远程下载，这样就不用先下载到程序所在的电脑上了。

**Comment by QiuChenly** [comment]
感谢建议，但是下载到本地并不符合程序设计的初衷，日后有时间我将尽力而为。

**Comment by StrollStars** [comment]
@QiuChenly 感谢回复，起初我也没想到这么用，只是后来发现在局域网上也可以访问有此想法，但是如果局域网上访问如果保存到本地，肯定不如本地访问来得快。
感谢开发者，这里先关闭了。
