### ISSUE TITLE
项目粉丝QQ交流群

### ISSUE THREAD

**Issue by QiuChenly** [QiuChenlyOpenSource/QQFlacMusicDownloader#93]
累积的欲望可以击穿顽石
ERROR

不准发黄图聊政治等负能量的东西，发发擦边活跃气氛可以不管你，但是禁止搞黄色，文明和谐交流，不想和谐的人我会先把你和谐掉。

U can join my QQ Group,but don't: 
1. Send Yellow Resource(e.g. shared av, but u can send private message to me like one-by-one chat.)
2. talking about political topics(because it will make anyone “Being summoned by online police to write a letter of repentance”，trust me, that's not good experience to u)
3. if u are Dinner,gck.
4. Silly Boy gck.
5. IQ <= 50 gck but Exclude RuoZhi吧吧u。
6. the SunXiaoChuan吧Green board little ghost GCK(level <= 1)

**Comment by hanhuajian** [comment]
白天工作太忙了   晚上空闲想起来  可发现已经closed了  可以把群发我tibuqijinzzc@gmail.com 吗  非dinner  想与大家交流

**Comment by SinisterD7** [comment]
Would like to join as well. 会文明讨论。gugusrk7@outlook.com
