### ISSUE TITLE
可以打开GUI界面，但是无法进行搜索

### ISSUE THREAD

**Issue by FlyingPolaris** [QiuChenlyOpenSource/QQFlacMusicDownloader#94]
可以正常运行MainServer，edge访问 http://127.0.0.1:8899 后，命令行界面出现如下的报错：
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/62804441/cb677f46-5b54-4bc7-985f-be45646331e7)
但是可以正常打开GUI界面：
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/62804441/9fa08884-7571-4ae9-aba8-93f3aa6a5499)
在搜索界面搜索任意关键字都无法显示搜索结果：
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/62804441/de80f48b-73cd-4ee7-99b2-62d89d3d4613)
F12显示错误信息如下：
![image](https://github.com/QiuChenlyOpenSource/QQFlacMusicDownloader/assets/62804441/b2bfc4af-47df-4f21-9c2a-c8ea6318bd09)

**Comment by QiuChenly** [comment]
我在前端界面忘记屏蔽本地测试接口ip地址了，等我重新推送一下

**Comment by QiuChenly** [comment]
已推送。
