### ISSUE TITLE
最新版本无法下载

### ISSUE THREAD

**Issue by VectorZhao** [QiuChenlyOpenSource/QQFlacMusicDownloader#99]
kw_token已生成 cdb524f42f0ce19b169b8072123a4727=sxMjyhnQi5Wc4Q22QfGb5frffwZF4DBC
 * Serving Flask app 'flaskSystem.App'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8899
 * Running on http://192.168.125.104:8899
Press CTRL+C to quit
192.168.125.103 - - [29/Jul/2023 08:00:39] "GET /index.html HTTP/1.1" 304 -
192.168.125.103 - - [29/Jul/2023 08:00:40] "GET /getConfig HTTP/1.1" 200 -
192.168.125.103 - - [29/Jul/2023 08:00:45] "GET /qq/search/经典/1/30 HTTP/1.1" 200 -
172.17.0.9 - - [29/Jul/2023 08:00:49] "POST /download HTTP/1.1" 200 -
192.168.125.103 - - [29/Jul/2023 08:00:50] "POST /download HTTP/1.1" 200 -
172.17.0.9 - - [29/Jul/2023 08:01:47] "POST /download HTTP/1.1" 200 -

**Comment by QiuChenly** [comment]
QQ接口已经被锁了

**Comment by VectorZhao** [comment]
这下不好搞了。。。
